language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - cd ui/app
  - npm install -g @angular/cli @angular/core @angular-builders/custom-webpack @angular-builders/dev-server @angular-devkit/build-angular dotenv
script:
  - ng lint
  - ng build
