language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - cd ui/app
  - npm install -g @angular/cli
  - npm install -g @angular/core
  - npm install --save-dev @angular-builders/custom-webpack
  - npm install --save-dev @angular-builders/dev-server
  - npm install --save-dev @angular-devkit/build-angular
  - npm install --save-dev dotenv
script:
  - ng build
