language: node_js
node_js:
  - "12"
sudo: required
#dist: trusty
branches:
  only:
    - master
#install:
#  - npm install -g protractor
before_script:
  - cd ui/app
  - npm install -g @angular/cli
  - npm install -g @angular/core
  - npm install --save-dev @angular-builders/custom-webpack
  - npm install --save-dev @angular-builders/dev-server
  - npm install --save-dev @angular-devkit/build-angular
  - npm install --save-dev dotenv
#  - webdriver-manager update
#  - webdriver-manager start --versions.chrome=87.0.4280.88 &
#  - sleep 3
addons:
  chrome: stable
#  firefox: latest
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-stable --allow-unauthenticated
cache:
  directories:
    - ./node_modules



script:
  - ng lint
  - ng build
  # run unit tests
  - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
  # run Protractor E2E tests
  - ng e2e --protractor-config=e2e/protractor-ci.conf.js
