language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - cd ui/app
  - npm install -g @angular/cli
  - npm install -g @angular/core
  - npm install --save-dev @angular-builders/custom-webpack
  - npm install --save-dev @angular-builders/dev-server
  - npm install --save-dev @angular-devkit/build-angular
  - npm install --save-dev dotenv
addons:
  chrome: stable
#  apt:
#    sources:
#      - google-chrome
#    packages:
#      - google-chrome-stable --allow-unauthenticated
cache:
  directories:
    - ./node_modules
#install:
#  - npm install
script:
  - ng lint
  - ng build
  # run unit tests
  - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
  # update Protractor and Selenium including ChromeDriver
  - npm run webdriver-update
  # launch Selenium standalone in the background
  - npm run webdriver-start
  # run Protractor E2E tests
  - ng e2e --protractor-config=e2e/protractor-ci.conf.js
